# Generated by Django 4.1 on 2022-09-07 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beds', models.IntegerField(default=0)),
                ('doctors', models.IntegerField(default=0)),
                ('nurses', models.IntegerField(default=0)),
                ('employees', models.IntegerField(default=0)),
                ('icus', models.IntegerField(default=0)),
                ('incubators', models.IntegerField(default=0)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosps.government')),
            ],
        ),
        migrations.CreateModel(
            name='HospType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurgType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hosp_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosps.hospdept')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosps.hospital')),
                ('surg_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosps.surgtype')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('empty_beds', models.IntegerField(default=0)),
                ('empty_icus', models.IntegerField(default=0)),
                ('empty_incubators', models.IntegerField(default=0)),
                ('absent_doctors', models.IntegerField(default=0)),
                ('absent_nurses', models.IntegerField(default=0)),
                ('absent_admins', models.IntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosps.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('procedure', models.CharField(max_length=200)),
                ('finished', models.BooleanField()),
                ('finished_date', models.DateField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosps.report')),
            ],
        ),
        migrations.CreateModel(
            name='Malfunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=50)),
                ('procedure', models.CharField(max_length=200)),
                ('finished', models.BooleanField()),
                ('finished_date', models.DateField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosps.report')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='hosp_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosps.hosptype'),
        ),
    ]
