# Generated by Django 4.1 on 2022-09-08 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosps', '0003_alter_hospital_hosp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gover', to='hosps.government'),
        ),
        migrations.AlterField(
            model_name='malfunction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='hosps.report'),
        ),
        migrations.AlterField(
            model_name='missing',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo1', to='hosps.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosp1', to='hosps.hospital'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='hosp_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospdep', to='hosps.hospdept'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosp', to='hosps.hospital'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surg_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosptyp', to='hosps.surgtype'),
        ),
    ]
