# Generated by Django 4.1 on 2022-09-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosps', '0004_alter_hospital_government_alter_malfunction_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hosp_dept',
            field=models.ManyToManyField(related_name='hospdept', to='hosps.hospdept'),
        ),
    ]
