# Generated by Django 4.1 on 2022-09-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosps', '0005_hospital_hosp_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hosp_dept',
            field=models.ManyToManyField(blank=True, related_name='hospdept', to='hosps.hospdept'),
        ),
    ]
