# Generated by Django 4.1 on 2022-09-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosps', '0007_alter_hospital_hosp_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hosp_dept',
        ),
    ]
